### ISSUE TITLE
Unsemantic italics

### ISSUE THREAD

**Issue by drgrigg** [hallidave/j-s-fletcher_scarhaven-keep#2]
Dave: we prefer if possible to keep bare `<i>` tags to a minimum, using `<em>` for emphasis and trying to either semantically tag things like book titles etc.

There are a few bare `<i>` tags left in your source which I think could be altered (but it's more a matter of preference than anything, so it's up to you). These are:

Chapter 18: line 53. `<i>Can you come?</i>`  This is a telegram, and the words would therefore have been in all-caps, so I think this could change to `<b>Can you come?</b>` Core.css will render this as capitals.

Same goes for Chapter 19: line 18 `<i>urgent business</i>`.

Chapter 9: line 18: The text of the message doesn't really need to be in italics, even if it is in the page source. Or you could semantically tag the italics with `epub:type="z3998:letter"`

Chapter 17: line 26: Since this is quoting the poster, I think it's probably reasonable to leave this as bare italics.

**Comment by hallidave** [comment]
Thanks. I've made all the changes you suggested.
