### ISSUE TITLE
Need to run typogrify again

### ISSUE THREAD

**Issue by drgrigg** [hallidave/j-s-fletcher_scarhaven-keep#3]
Running typogrify results in changes in several files, which you should accept. Mainly they are hairspaces around dashes, etc.

**Comment by hallidave** [comment]
Done. There are two changes I didn't accept: 1) chapter 17, line 26 (incorrectly changed some of the dots to ellipsis), and 2) chapter 27, line 26 (incorrectly changed apostrophe to single quote).
